baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Galerie Klein'

[[menus.main]]
name = 'News'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Shows'
pageRef = '/shows'
weight = 10

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
